### ISSUE TITLE
[QUESTION] Production Ready

### ISSUE THREAD

**Issue by arminsal1** [sjones6/gun-realm#1]
What about this library is preventing it from being production ready?

Would love to integrate GUN with Realm for my app!

**Comment by sjones6** [comment]
I haven't used this for quite some time and/or deployed used it in a production environment. If you ran tests against it to make sure that things were scalable, performant, secure, etc. then it would be "production" ready.

**Comment by arminsal1** [comment]
Gotcha, thanks for the prompt response!

**Comment by sjones6** [comment]
Sure thing. Closing this issue. 

Let me know if you do the leg work to make this production ready.
